# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

steps:


- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install Dependencies'
  inputs:
    command: 'install'
    workingDir: 'src/forgedinthelore-ng'

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: 'custom'
    workingDir: 'src/forgedinthelore-ng'
    customCommand: 'run build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'src/forgedinthelore-ng/dist'

- task: DeleteFiles@1
  displayName: 'Delete JUnit files'
  inputs:
    SourceFolder: src/forgedinthelore-ng/junit
    Contents: 'TEST*.xml'

- task: Npm@1
  displayName: 'Test Angular'
  inputs:
    command: 'custom'
    customCommand: 'run test -- --watch=false --code-coverage --karmaConfig src/karma.conf.ci.js'
    workingDir: 'src/forgedinthelore-ng'

- task: PublishTestResults@2
  displayName: 'Publish Angular test results'
  condition: succeededOrFailed()
  inputs:
    searchFolder: $(System.DefaultWorkingDirectory)/src/forgedinthelore-ng/junit
    testRunTitle: Angular
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage Angular results'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/forgedinthelore-ng/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/src/forgedinthelore-ng/coverage'
    failIfCoverageEmpty: false
