# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureSubscription: 'Microsoft Internal Subscription 1(GUID)'
  
  # Environment name
  environmentName: 'test'
  # Project name
  projectName: 'forgedinthelore-ng'
  # Web app name
  webAppName: 'forged-in-the-lore'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          cd '$(Build.SourcesDirectory)/$(projectName)'
          npm install -g @angular/cli
          npm install
          ng build --prod
        displayName: 'npm install and build'
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/$(projectName)/dist/$(webAppName)/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: 'ubuntu-20.04'
    environment: $(environmentName)
#    strategy:
#      runOnce:
#        deploy:
#          steps:
     
#          - task: AzureWebApp@1
#            displayName: 'Deploy Azure Web App : $(webAppName)'
#            inputs:
#              azureSubscription: $(azureSubscription)
#              appName: $(webAppName)
#              appType: webAppLinux
#              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip 